apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argo-argo-andrei
  namespace: argoandrei
spec: 
  project: default 
  source: 
    repoURL: https://github.com/AndreiMusca00/argoGolang.git
    targetRevision: main 
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argoma
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
       