apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env: 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-secret-postgres
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: user
                name: postgres-config
          - name: POSTGRES_DB 
            valueFrom:
              configMapKeyRef:
                key: db
                name: postgres-config